# ~/.config/hypr/hyprland.conf

$mainMod = SUPER
$terminal = ghostty

monitor = , preferred, auto, 1

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, E, exit

# --- Input ---
input {
	kb_layout = us
	follow_mouse = 1
	touchpad {
		natural_scroll = true
		tap-to-click = true
		disable_while_typing = true
	}
}

# --- Layout & borders ---
general {
	gaps_in = 5
	gaps_out = 12
	border_size = 2
	layout = dwindle
	col.active_border = rgba(cba6f7ee) rgba(89b4faee) 45deg
	col.inactive_border = rgba(585b70aa)
}

# --- decoration ---
decoration {
	rounding = 10
	blur {
		enabled = true
		size = 3
		passes = 1
	}
}

# --- Window binds ---
bind = $mainMod, V, togglefloating
bind = $mainMod, F, fullscreen
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# --- Workspaces ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# --- Mouse drag (move/resize) ---
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# --- menu ---
$menu = rofi -show drun
bind = $mainMod, D, exec, $menu

# --- Autostart ---
exec-once = swaybg -c 1e1e2e
# exec-once = swaybg -m fill -i ~/Pictures.wallpaper.png
exec-once = waybar
exec-once = mako
