-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ~/.config/hypr/hyprland.conf

local mainMod = "SUPER"

local terminal = "ghostty"

hl.monitor({
  output = "",
  mode = "preferred",
  position = "auto",
  scale = 1,
})

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

-- --- Input ---

hl.config({
  input = {
    kb_layout = "us",
    follow_mouse = 1,
    touchpad = {
      natural_scroll = true,
      tap_to_click = true,
      disable_while_typing = true,
    },
    numlock_by_default = true,
  },
  misc = {
    mouse_move_enables_dpms = true,
    key_press_enables_dpms = true,
  },
})

-- --- Layout & borders ---

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 12,
    border_size = 2,
    layout = "dwindle",
    col = {
      active_border = { colors = { "rgba(cba6f7ee)", "rgba(89b4faee)" }, angle = 45 },
      inactive_border = "rgba(585b70aa)",
    },
  },
})

-- --- decoration ---

hl.config({
  decoration = {
    rounding = 10,
    blur = {
      enabled = true,
      size = 3,
      passes = 1,
    },
  },
})

-- --- Window binds ---

hl.bind(mainMod .. " + " .. " SHIFT" .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.move({ direction = "l" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.move({ direction = "r" }))

hl.bind(
  mainMod .. " + " .. "V",
  hl.dsp.exec_cmd("cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy")
)

-- --- Workspaces ---

for i = 1, 10 do
  local key = tostring(i % 10) -- workspace 10 → key 0
  hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- --- Special workspace ---
hl.bind(mainMod .. " + grave", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + grave", hl.dsp.window.move({ workspace = "special:magic" }))

-- --- Mouse drag (move/resize) ---

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- --- menu ---

local menu = "rofi -show drun"

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd(menu))

-- emojis and special characters

hl.bind(mainMod .. " + " .. "period", hl.dsp.exec_cmd("rofimoji --selector rofi"))

-- --- screenshots ---

local screenshot = "grimblast --freeze copysave area"
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd(screenshot))

-- --- wallpaper ---
local wallreload = os.getenv("HOME") .. "/.local/bin/randwall"
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd(wallreload))

-- --- Autostart ---

-- Autostart
hl.on("hyprland.start", function()
  hl.exec_cmd(wallreload .. " 30m")
  hl.exec_cmd("waybar")
  hl.exec_cmd("mako")
end)

-- start/stop hooks
hl.on("hyprland.start", function()
  hl.exec_cmd("/usr/libexec/hyprpolkitagent")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("hypridle")
end)

-- session start/stop (init-system specific; resolved by  yadm per machine)
local session = dofile(os.getenv("HOME") .. "/.config/hypr/session.lua")
session(hl)

-- Special window rules
hl.window_rule({
  match = { class = "hyprpolkitagent" },
  float = true,
  center = true,
})

-- Cursors
hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-mauve-cursors")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "catppuccin-mocha-mauve-cursors")
hl.env("XCURSOR_SIZE", "24")

-- --- Monitor placement ---
pcall(require, "monitors")

-- Environment Vars
hl.env("DEFAULT_TARGET_DIR", "/tmp/screenshots")
hl.env("SAL_USE_VCLPLUGIN", "qt6")
hl.env("BIBINPUTS", "/home/indyg/notes/refs:")

-- Qt theming (Kvantum / Catppuccin Mocha)
hl.env("QT_QPA_PLATFORMTHEME", "kvantum")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

-- Wine
hl.env("PATH", "/etc/eselect/wine/bin:" .. (os.getenv("PATH") or ""))

-- --- Media / volume keys (Corsair VOID v2) ---

hl.bind(
  "XF86AudioRaiseVolume",
  hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"),
  { locked = true, repeating = true }
)

hl.bind(
  "XF86AudioLowerVolume",
  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
  { locked = true, repeating = true }
)

hl.bind("code:172", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
