background {
  monitor =
  # path = ~/.config/hypr/lockscreen.png
  color = rgba(30, 30, 46, 1.0)
  blur_passes = 2
  blur_size = 4
}

input-field {
  monitor =
  size = 264, 55
  outline_thickness = 2
  dots_size = 0.33
  dots_spacing = 0.15
  dots_center = true
  outer_color = rgba(203, 166, 247, 1.0)
  inner_color = rgba(49, 50, 68, 1.0)
  font_color = rgba(205, 214, 244, 1.0)
  check_color = rgba(166, 227, 161, 1.0)
  fail_color = rgba(243, 139, 168, 1.0)
  fade_on_empty = true
  placeholder_text = <i>Password...</i>
  font_family = DepartureMono Nerd Font
  position = 0, -20
  halign = center
  valign = center
}

label {
  monitor =
  text = $TIME
  color = rgba(205, 214, 244, 1.0)
  font_family = DepartureMono Nerd Font
  font_size = 88
  position = 0, 110
  halign = center
  valign = center
}

label {
  monitor = 
  text = Hi there, $USER
  color = rgba(186, 194, 222, 1.0)
  font_family = DepartureMono Nerd Font
  font_size = 22
  position = 0, 44
  halign = center
  valign = center
}
