background = 0xFF1e1e2e
base = 0xFF181825
text = 0xFFcdd6f4
alternate_base = 0xFF313244
bright_text = 0xFFf5e0dc
accent = 0xFFcba6f7
accent_secondary = 0xFF89b4fa
font_family = DepartureMono Nerd Font
fontsize = 11
small_font_size = 11
h1_size = 22
h2_size = 11
h3_size = 11
